apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: llama-swappo-halo-latest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: llama-swappo-halo
  policy:
    semver:
      range: '>=0.1.0'
