apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # image-policy.yaml  # Disabled - requires Flux image automation controllers
  # image-repository.yaml  # Disabled - requires Flux image automation controllers
  - infrastructure
  - apps
