apiVersion: v1
kind: Service
metadata:
  name: llama-swappo-halo
  namespace: default
  labels:
    app: llama-swappo-halo
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.68.100
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: llama-swappo-halo
